### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ChaoticTabris** [mosharky/Ongoing-Patches#10]
### Group

Rodryk's Dragon Bridge, The Great Cities of JK's North

### Describe your issue. Please provide your load order using Load Order Library if applicable.

I'm getting the following error when using LOOT with your TGCoJN + Rodryk's Dragon Bridge patch

![image](https://github.com/mosharky/Ongoing-Patches/assets/10170803/3cf23129-117b-4339-a7b9-58e1cfe21cfe)

**Comment by mosharky** [comment]
Fixed in the next update
