### ISSUE TITLE
[Bug]:  ((The Great Cities of JK's North - Patch)) This mode has been updated to the latest version

### ISSUE THREAD

**Issue by dlstmdzm** [mosharky/Ongoing-Patches#7]
### Group

The Great Cities of JK's North

### Describe your issue. Please provide your load order using Load Order Library if applicable.

https://arca.live/b/tullius/69561514?p=1

Please look at this picture.

((The Great Cities of JK's North - Patch)) This mode has been updated to the latest version. If you use this mode with the latest version, the terrain will be ruined as shown in the picture. Please modify it to be compatible. I beg you.

### Crash report/logs

https://arca.live/b/tullius/69561514?p=1

**Comment by mosharky** [comment]
i dont touch landscape records at all lol
