### ISSUE TITLE
[Patch Request]: skyrim arrow overhaul

### ISSUE THREAD

**Issue by DJLegends1011** [mosharky/Ongoing-Patches#8]
### Describe your patch request

will need to update your skyrim arrow overhaul patches since it no longer use outfit records

### Checklist

- [X] Does not already exist
- [X] Would only contain ESPs or mesh fixes
- [X] Was not already requested
- [X] Is not a symptom of a load order issue (if unsure, its okay to leave unticked)
- [X] May not be considered

**Comment by mosharky** [comment]
ah yeah I still need to get on this. Idk when I'll get the skyrim itch again, sorry

**Comment by mosharky** [comment]
Should be fixed in the next update
