### ISSUE TITLE
[Bug]: Floating Firepit in Winterhold

### ISSUE THREAD

**Issue by Innocenciusxvi** [mosharky/Ongoing-Patches#9]
### Group

The Great Cities of JK's North

### Describe your issue. Please provide your load order using Load Order Library if applicable.

![enb2023_5_6_22_41_00](https://user-images.githubusercontent.com/105151770/236660083-653c164f-1564-4657-9a9c-61b68e9259dc.jpg)
![enb2023_5_6_22_41_05](https://user-images.githubusercontent.com/105151770/236660115-d25750ab-5893-4c1f-a075-46820d47ca18.jpg)

**Comment by mosharky** [comment]
Fixed in the next patch, thanks for reporting!
